# Generated by Django 5.1.7 on 2025-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Phone Number'),
        ),
    ]
