# Generated by Django 5.1.7 on 2025-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_shopuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
