# Generated by Django 5.1.7 on 2025-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
