# Generated by Django 5.1.7 on 2025-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_comment_rate_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(null=True, verbose_name='Total Price'),
        ),
    ]
